### ISSUE TITLE
Write-unsafe context

### ISSUE THREAD

**Issue by krasa** [SeeSharpSoft/intellij-file-preview#2]
```
java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities:
    ModalityState:{}, writingAllowed=true;
    ModalityState.NON_MODAL, writingAllowed=true;
    ModalityState:{}, writingAllowed=true;
    ModalityState:{}, writingAllowed=true;
    ModalityState:{}, writingAllowed=true;
    ModalityState:{}, writingAllowed=true;
    ModalityState:{}, writingAllowed=true
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:862)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$7(FileEditorManagerImpl.java:845)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:630)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:643)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:845)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:790)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$4(FileEditorManagerImpl.java:773)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:773)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:704)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:139)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewProjectHandler$1.valueChanged(PreviewProjectHandler.java:44)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:625)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.JTree.setSelectionPaths(JTree.java:1669)
	at java.desktop/javax.swing.JTree.setSelectionRows(JTree.java:1752)
	at java.desktop/javax.swing.JTree.setSelectionRow(JTree.java:1727)
	at com.intellij.util.ui.tree.TreeUtil.lambda$showAndSelect$10(TreeUtil.java:594)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:629)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:539)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:530)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentred(TreeUtil.java:525)
	at com.intellij.util.ui.tree.TreeUtil.selectPath(TreeUtil.java:456)
	at com.intellij.util.ui.tree.TreeUtil.selectPath(TreeUtil.java:449)
	at com.intellij.ide.projectView.impl.AsyncProjectViewSupport.selectPaths(AsyncProjectViewSupport.java:210)
	at com.intellij.ide.projectView.impl.AsyncProjectViewSupport.lambda$null$2(AsyncProjectViewSupport.java:173)
	at org.jetbrains.concurrency.AsyncPromise$onProcessed$1.accept(AsyncPromise.kt:85)
	at org.jetbrains.concurrency.AsyncPromise$onProcessed$1.accept(AsyncPromise.kt:13)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.jetbrains.concurrency.AsyncPromise.setResult(AsyncPromise.kt:130)
	at com.intellij.ui.tree.AbstractTreeWalker.processNextPath(AbstractTreeWalker.java:149)
	at com.intellij.ui.tree.AbstractTreeWalker.start(AbstractTreeWalker.java:109)
	at com.intellij.ui.tree.AbstractTreeWalker.start(AbstractTreeWalker.java:92)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:58)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:13)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:55)
	at com.intellij.ui.tree.AsyncTreeModel.lambda$null$7(AsyncTreeModel.java:284)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:145)
	at com.intellij.util.concurrency.Invoker.lambda$invokeLater$0(Invoker.java:91)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
IJ 2019.2

**Comment by SeeSharpSoft** [comment]
@krasa Thanks for reporting. Which plugin version did you test? There was some rapid development going on, I currently can not reproduce it with 1.1.

**Comment by krasa** [comment]
1.0

**Comment by krasa** [comment]
reproduced with 1.1
```
java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities:
    ModalityState:{}, writingAllowed=true;
    ModalityState:{}, writingAllowed=true;
    ModalityState:{}, writingAllowed=true;
    ModalityState:{}, writingAllowed=true;
    ModalityState.NON_MODAL, writingAllowed=true;
    ModalityState:{}, writingAllowed=true
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:862)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$7(FileEditorManagerImpl.java:845)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:630)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:643)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:845)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:790)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$4(FileEditorManagerImpl.java:773)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:773)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:704)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:139)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewProjectHandler$1.valueChanged(PreviewProjectHandler.java:44)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:625)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.JTree.setSelectionPaths(JTree.java:1669)
	at java.desktop/javax.swing.JTree.setSelectionRows(JTree.java:1752)
	at java.desktop/javax.swing.JTree.setSelectionRow(JTree.java:1727)
	at com.intellij.util.ui.tree.TreeUtil.lambda$showAndSelect$10(TreeUtil.java:594)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:644)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:539)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:530)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentred(TreeUtil.java:525)
	at com.intellij.util.ui.tree.TreeUtil.selectPath(TreeUtil.java:456)
	at com.intellij.util.ui.tree.TreeUtil.selectPath(TreeUtil.java:449)
	at com.intellij.ide.projectView.impl.AsyncProjectViewSupport.selectPaths(AsyncProjectViewSupport.java:210)
	at com.intellij.ide.projectView.impl.AsyncProjectViewSupport.lambda$null$2(AsyncProjectViewSupport.java:173)
	at org.jetbrains.concurrency.AsyncPromise$onProcessed$1.accept(AsyncPromise.kt:85)
	at org.jetbrains.concurrency.AsyncPromise$onProcessed$1.accept(AsyncPromise.kt:13)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.jetbrains.concurrency.AsyncPromise.setResult(AsyncPromise.kt:130)
	at com.intellij.ui.tree.AbstractTreeWalker.processNextPath(AbstractTreeWalker.java:149)
	at com.intellij.ui.tree.AbstractTreeWalker.setChildren(AbstractTreeWalker.java:67)
	at com.intellij.ui.tree.AsyncTreeModel$2.lambda$getChildren$0(AsyncTreeModel.java:277)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:58)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:13)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.jetbrains.concurrency.AsyncPromise.setResult(AsyncPromise.kt:130)
	at com.intellij.ui.tree.AsyncTreeModel$CommandQueue.lambda$done$0(AsyncTreeModel.java:769)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.intellij.ui.tree.AsyncTreeModel$CommandQueue.done(AsyncTreeModel.java:769)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.setNode(AsyncTreeModel.java:726)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.accept(AsyncTreeModel.java:490)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.accept(AsyncTreeModel.java:445)
	at com.intellij.util.concurrency.Command$Processor.lambda$consume$0(Command.java:40)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:145)
	at com.intellij.util.concurrency.Invoker.lambda$invokeLater$0(Invoker.java:91)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by SeeSharpSoft** [comment]
Can you provide any more information, like:
- Do you get this exception when selecting any file?
- Is an editor ever opened?
- Is IJ = IC (see _type_ in https://github.com/JetBrains/gradle-intellij-plugin/#intellij-platform-properties)?
- Do you have any other plugins that might influence how the editors are opened?
- Are you using the packaged version or from source code?

Thanks!

**Comment by krasa** [comment]
- It is quite random, different files, I open them, edit them open different ones and it just happens.
- yes, always. 
- IC
- you tell me :)
- from https://github.com/SeeSharpSoft/intellij-file-preview/releases

I have a feeling that it happens when `Scroll from source` is enabled, but can't be sure.  Maybe just wrap the whole thing into #invokeLater?

`
IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 7433M
Cores: 8
Registry: ide.max.recent.projects=1001, java.completion.argument.hints.internal=false, git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: BrowseWordAtCaret, Builder Generator, CMD Support, Context Console Plugin, EclipseCodeFormatter, EditorGroups, FrameSwitcher, IdeBenchmarker, PlantUML integration, ProjectCommandLauncher, PsiViewer, RetardedButtonsFix, Scratch, Shifter, Statistic, String Manipulation, VisualVMLauncher, YourKit Java Profiler 2018.04-b75 Integration, com.andrewbrookins.wrap_to_column, com.bulenkov.idea.Idea11IconPack, com.dpaulenk.idea.contexthelp, com.jetbrains.colorful.toolwindow.icons, com.jetbrains.intellij.file-manager, com.tobszarny.activetabhighlighter.plugin.id, dcevm, krasa.CpuUsageIndicator, krasa.IdeaIconPack, krasa.translatorGenerator, net.seesharpsoft.intellij.plugins.file-preview, org.asciidoctor.intellij.asciidoc, org.intellij.scratch, org.jetbrains.idea.grammar, io.gulp.intellij, UsefulActions, org.jetbrains.kotlin, LivePlugin, MavenRunHelper, pl.micdev.intellij.fluentsetter, ru.artyushov, ru.yole.jitwatch-intellij
`

**Comment by SeeSharpSoft** [comment]
@krasa Nice - it seems that the _"edit them"_ part was actually the important missing piece, I just tested opening files without editing. Could you please double check whether this exception occurs if you just browse arbitrarily through the files in your Project View without editing them. Thanks again!

**Comment by krasa** [comment]
It happens even without editing. 

Look into `TransactionGuard`  and how it is implemented in `com.intellij.ui.AutoScrollToSourceHandler`. You just cannot be on a plain swing EDT.

`ApplicationManager.getApplication().invokeLater` would solve it.

**Comment by krasa** [comment]
btw you should probably delegate everything you can in `PreviewVirtualFile` to `source` - e.g `#getParent` breaks other plugins. And make PreviewStartupActivity implement DumbAware.

**Comment by SeeSharpSoft** [comment]
@krasa Thanks alot for the `TransactionGuard` hint - I re-used the code from `AutoScrollToSourceHandler` now.

> btw you should probably delegate everything you can in PreviewVirtualFile to source - e.g #getParent breaks other plugins

This is not the intention of the `PreviewVirtualFile` - it is not a wrapper. It should act as a different kind of file then the original source on purpose, mainly to ensure that `PreviewFileEditorProvider` handles its `FileEditor` creation. `PreviewFileEditorProvider` "unwraps" it then to provide the source to the actual `FileEditorProvider`.

**Comment by krasa** [comment]
Well, but it is a wrapper. And it is passed into `com.intellij.openapi.fileEditor.FileEditorManagerListener#fileOpenedSync`, where it breaks my plugin. :-)

Generating delegating methods won't hurt anything.

**Comment by krasa** [comment]
Or you could probably put a flag into VirtualFile#userData instead using that wrapper.

**Comment by SeeSharpSoft** [comment]
> Generating delegating methods won't hurt anything.

Unfortunately thats not true :( - it does in this case. I tried delegating all methods to the source and it breaks.

Which of your plugins does it break? I will use it for testing purposes.

**Comment by SeeSharpSoft** [comment]
> Or you could probably put a flag into VirtualFile#userData instead using that wrapper.

I basically tried it but the problem is, that the FileEditorManager will just ignore when the file is actullay opened for good (e.g. by double-click). Having a virtual preview file seems somewhat right to me. However, I am with you that I need to invest some time and effort in providing the correct information in its implementation, e.g. `getOutputStream` is annotated by `NotNull` but returns `null`.

Thanks for all your help and suggestions! I am always open for more ideas.

**Comment by SeeSharpSoft** [comment]
Latest commit tackles this issue: 7f2a22b8e3cb2e79f12c5d77e8fe667fe5796627

**Comment by krasa** [comment]
> I tried delegating all methods to the source and it breaks.

Ok, so maybe not all methods :-)

https://plugins.jetbrains.com/plugin/10897-editor-groups  - all it really needs is #getParent in FileEditorManagerListener, so you don't need to install it. 

Yeah, having that wrapper is probably better, but as you see, not without risks.

**Comment by SeeSharpSoft** [comment]
> all it really needs is #getParent in FileEditorManagerListener

Ok, I can give you that ;)

**Comment by krasa** [comment]
Thanks :)
