### ISSUE TITLE
2024.2 BUG

### ISSUE THREAD

**Issue by wdkGitHub** [SeeSharpSoft/intellij-file-preview#97]
```
java.lang.IllegalArgumentException: Illegal transform definition 'rotate(360deg)' encountered error while parsing 'rotate(360deg)'
	at com.github.weisj.jsvg.attributes.AttributeParser.parseTransform(SourceFile:238)
	at com.github.weisj.jsvg.parser.AttributeNode.g(SourceFile:285)
	at com.github.weisj.jsvg.ci.a(SourceFile:63)
	at com.github.weisj.jsvg.bn.build(SourceFile:54)
	at com.github.weisj.jsvg.bl.build(SourceFile:64)
	at com.github.weisj.jsvg.bm.build(SourceFile:70)
	at com.github.weisj.jsvg.nodes.SVG.build(SourceFile:104)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:115)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.buildDocument(JSvgDocumentFactory.kt:110)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:37)
	at com.intellij.ui.svg.SvgKt.renderImage(svg.kt:288)
	at com.intellij.ui.svg.SvgKt.renderAndCache(svg.kt:258)
	at com.intellij.ui.svg.SvgKt.access$renderAndCache(svg.kt:1)
	at com.intellij.ui.svg.SvgKt.loadSvgAndCacheIfApplicable-F6nGey4(svg.kt:567)
	at com.intellij.ui.icons.ImageCacheKt.doLoadByDescriptor(imageCache.kt:241)
	at com.intellij.ui.icons.ImageCacheKt.loadByDescriptorWithoutCache(imageCache.kt:148)
	at com.intellij.ui.icons.ImageCacheKt.loadImage(imageCache.kt:111)
	at com.intellij.ui.icons.ImageCacheKt.loadImage$default(imageCache.kt:64)
	at com.intellij.ui.icons.ImageDataByPathResourceLoader.loadImage(ImageDataByUrlLoader.kt:67)
	at com.intellij.ui.icons.CachedImageIcon.loadImage-Xbo1f9k$intellij_platform_util_ui(CachedImageIcon.kt:330)
	at com.intellij.ui.icons.ScaledIconCache.loadIcon-GvFvY-8(ScaledIconCache.kt:58)
	at com.intellij.ui.icons.ScaledIconCache.getCachedIcon-BVbfYdY(ScaledIconCache.kt:43)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:166)
	at com.intellij.ui.icons.CachedImageIcon.getIconWidth(CachedImageIcon.kt:127)
	at com.intellij.ui.RowIcon.updateSize(RowIcon.kt:142)
	at com.intellij.ui.RowIcon.paintIcon(RowIcon.kt:96)
	at com.intellij.ui.svg.SvgKt.paintIconWithSelection(svg.kt:361)
	at com.intellij.util.IconUtil.paintSelectionAwareIcon(IconUtil.kt:248)
	at com.intellij.ui.SimpleColoredComponent.paintIcon(SimpleColoredComponent.java:1089)
	at com.intellij.ui.SimpleColoredComponent.doPaintIcon(SimpleColoredComponent.java:801)
	at com.intellij.ui.SimpleColoredComponent.doPaint(SimpleColoredComponent.java:761)
	at com.intellij.ui.SimpleColoredComponent.paintComponent(SimpleColoredComponent.java:745)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:170)
	at com.intellij.ui.tree.ui.DefaultTreeUI.paint(DefaultTreeUI.java:373)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:855)
	at com.intellij.ui.treeStructure.Tree.paintComponent(Tree.java:379)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at com.intellij.ui.treeStructure.Tree.paint(Tree.java:310)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:240)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at com.intellij.ui.components.JBScrollPane.paintChildren(JBScrollPane.java:242)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at com.intellij.ui.components.JBScrollPane.paint(JBScrollPane.java:230)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1680)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1655)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1592)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:272)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1352)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5267)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5077)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:887)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:870)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:870)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:843)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:789)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1921)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:389)
	at com.intellij.openapi.progress.impl.PlatformTaskSupportKt.pumpEventsForHierarchy(PlatformTaskSupport.kt:399)
	at com.intellij.openapi.progress.impl.PlatformTaskSupportKt.pumpEventsForHierarchy(PlatformTaskSupport.kt:407)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImplKt$blockingWaitForCompositeFileOpen$2.invokeSuspend(FileEditorManagerImpl.kt:2437)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:111)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$BuildersKt__BuildersKt(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:52)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImplKt.blockingWaitForCompositeFileOpen(FileEditorManagerImpl.kt:2432)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl$intellij_platform_ide_impl(FileEditorManagerImpl.kt:1143)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFile(FileEditorManagerImpl.kt:904)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.kt:145)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.lambda$openPreviewOrEditor$2(PreviewUtil.java:154)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.lambda$invokeSafeAndWait$0(PreviewUtil.java:106)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:836)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:404)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:437)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.invokeSafeAndWait(PreviewUtil.java:104)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.openPreviewOrEditor(PreviewUtil.java:153)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.lambda$openPreviewOrEditor$3(PreviewUtil.java:163)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.lambda$null$5(PreviewUtil.java:205)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:46)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:67)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.lambda$consumeDataContext$6(PreviewUtil.java:204)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:86)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.consumeDataContext(PreviewUtil.java:204)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.openPreviewOrEditor(PreviewUtil.java:162)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.openPreviewOrEditor(PreviewUtil.java:168)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewProjectHandler.lambda$openOrFocusSelectedFile$7(PreviewProjectHandler.java:211)
	at net.seesharpsoft.intellij.plugins.filepreview.PreviewUtil.lambda$invokeSafe$1(PreviewUtil.java:114)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:836)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:425)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1162)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.IllegalStateException: Unexpected token '' rest=deg(index=3 in input=360deg)
	at com.github.weisj.jsvg.dk.i(SourceFile:98)
	at com.github.weisj.jsvg.attributes.AttributeParser.parseDoubleList(SourceFile:161)
	at com.github.weisj.jsvg.attributes.AttributeParser.parseTransform(SourceFile:1250)
	... 203 more
Caused by: java.lang.NumberFormatException: empty String
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:792)
	at com.github.weisj.jsvg.dk.i(SourceFile:93)
	... 205 more

```

**Comment by weisJ** [comment]
The svg file you are trying to preview contains an invalid `transform` value of `rotate(360deg)`. The svg specification does not support specifying rotation in `deg` units. Replace with with `rotate(360)` (or remove it completely as it doesn't do anything anyways).
